### ISSUE TITLE
Typo in installation instructions

### ISSUE THREAD

**Issue by dudaerich** [ochaloup/vim-syntax-match#1]
> Now the installation of this plugin is easy like
>     git clone git@github.com:ochaloup/vim-syntax-match.git ~/.vim/autoload/vim-syntax-match

This doesn't work for me. Documentation page on [pathogen](http://www.vim.org/scripts/script.php?script_id=2332) says:
> Now any plugins you wish to install can be extracted to a subdirectory under ~/.vim/bundle, and they will be added to the 'runtimepath'. 

So I think the correct command should be:
```
git clone git@github.com:ochaloup/vim-syntax-match.git ~/.vim/bundle/vim-syntax-match
```

**Comment by ochaloup** [comment]
ah, correct. Sorry for inconveniences. That was some copy&paste mistake. It should be fixed now. Thanks!
